### ISSUE TITLE
I cant install - Help!

### ISSUE THREAD

**Issue by SereiaMaster** [yiisoft/yii-mssql#2]
### Additional info

| Q                    | A
| -------------------- | ---
| Yii version         |2.0.16 
| PHP version         | 7.2
| Operating system     |Win 10

Showing this...

`yiisoft/core 3.0.x-dev requires psr/container-implementation ^1.0 -> no matching package found.`

**Comment by samdark** [comment]
If you're using Yii 2.0.16, MSSQL is included. You don't need to install anything.
